baseURL = 'https://Jono-Moss.github.io'
languageCode = 'en-us'
title = 'Jonathan Moss'
theme="hugo-theme-stack"

[markup]
  [markup.goldmark]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'autumn'
    tabWidth = 4
